Added Jupyter notebook demos
OpenACCUserGroup/openacc_concept_strategies_book pull request #5
Opened 2018-10-22 22:05 UTC by noahrossi

I created these for Professor Sunita over the last summer. These notebooks should be able to run all of the examples from the book within Jupyter. I used the Readme files when possible and improvised when those weren't available.

Please let me know if you need any changes. Thanks!

2018-10-24 19:46 UTC, juckel requested changes
Noah,

thanks a lot for this work, which really improves the additional material for the book.
I kindly ask for a few changes to accept this pull request:
- you committed a couple of hidden files (like .gitignore, .ipynb_ckckpoints), those should be removed from the commit
- you also added a couple of binary files (e.g. Code_Examples/Chapter_02/area.ser etc.), these need to be removed from the commit as they will be built by the user
- you put all your work in the flat directories of each chapter. To keep things separate, I would recommend creating a subdirectory "python-notebook" under each chapter and move your work there
- your work should contain a small readme (or prerequisite section at the beginning of the notebook) explaining that the PGI compiler is required to be installed for the notebooks to work (and maybe a link to how to get it). Also a documentation on how to start the notebooks is helpful. Hence, I recommend adding a readme.md to each of your newly created "python-notebook" subdirectories, since that will be automatically displayed by GitHub

Again - thanks a lot for all the work. And I appreciate you taking the time for these few minor fixes!
Guido

2018-11-06 18:43 UTC, noahrossi commented
Hi,

Sorry for the delay in these changes, but here they are! I think I covered all of your changes, but please let me know if you need anything else tweaked.

Thanks again!
Noah

2018-11-08 12:34 UTC, juckel approved these changes

2018-11-08 12:38 UTC, juckel approved these changes

2018-11-08 12:38 UTC, merged